name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Lint, Test & Coverage on Node ${{ matrix.node }} / ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        include:
          - node: '18.x'
            os: ubuntu-latest
          - node: '18.x'
            os: windows-latest
          - node: '20.x'
            os: ubuntu-latest
          - node: '20.x'
            os: windows-latest
          - node: '20.x'
            os: macOS-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Create a unique flag name per job, so Coveralls can combine them later.
          # Replace slashes and dots so the flag has no special characters
          flag-name: ${{ matrix.os }}-node${{ matrix.node }}
          parallel: true

      - name: Build
        run: yarn build

  finish:
    name: Notify Coveralls – all parallel jobs done
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify Coveralls parallel-finished
        uses: coverallsapp/github-action@v2
        with:
          # Signal Coveralls that all "flag-name" uploads are complete
          parallel-finished: true
          carryforward: |
            ubuntu-latest-node18.x,
            windows-latest-node18.x,
            ubuntu-latest-node20.x,
            windows-latest-node20.x,
            macOS-latest-node20.x
